modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL="https://github.com/alec016/Degrassi/issues"

[[mods]]
modId = "degrassi"
version = "${version}"
displayName = "Degrassi"
logoFile = "icon.png"
authors="Alec_016GG"
description = '''
Degrassi Mod
'''

[[dependencies.degrassi]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.degrassi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.degrassi]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.degrassi]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.degrassi]]
modId = "geckolib3"
mandatory = true
versionRange = "[${geckolib_version},)"
ordering = "AFTER"
side = "BOTH"
