modLoader = "javafml"
loaderVersion = "[47.2.0,)"
license = "MIT"
issueTrackerURL="https://github.com/alec016/Degrassi/issues"

[[mods]]
modId = "degrassi"
version = "${version}"
displayName = "Degrassi"
logoFile = "icon.png"
authors="Alec_016GG"
description = '''
Degrassi Mod
'''

[[dependencies.degrassi]]
modId = "forge"
mandatory = true
versionRange = "[47.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.degrassi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1, 1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.degrassi]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.degrassi]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"
