name: Bug Report
description: Report a bug with Degrassi
labels: [ bug ]
body:
  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
      placeholder: "Ex: 1.19.2"
    validations:
      required: true

  - type: input
    id: degrassi-version
    attributes:
      label: Degrassi Version
      placeholder: "Ex: Degrassi-1.19.2-1.0.0"
    validations:
      required: true

  - type: input
    id: arch-version
    attributes:
      label: Architectury Version
      placeholder: "Ex: 3.3.6"
    validations:
      required: true

  - type: input
    id: loader-version
    attributes:
      label: Forge Version
      placeholder: "Ex: Forge 26.2.22"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Issue Description"

  - type: textarea
    id: description
    attributes:
      label: Describe your issue
    validations:
      required: true

  - type: input
    id: logs
    attributes:
      label: Crash report/logs
      description: Paste a link to the crash report or latest.log, if required
