# blank_issues_enabled: false
# contact_links:
#   - name: Discord
#     url: https://discord.gg/lat
#     about: Looking for general scripting help, or more examples? Ask in one of the support channels!
#   - name: Wiki
#     url: https://kubejs.com/
#     about: How to get started with KubeJS scripts and some examples!
